In [9]:
import numpy as np

In [10]:
matriz_cuadrada = np.array([
    [ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11],
    [12, 13, 14, 15]
])

matriz_no_cuadrada = np.array([
    [ 0,  1,  2,  3],
    [12, 13, 14, 15]
])

Ejercicio 1. Desarrollar una función esCuadrada(A) que devuelva verdadero si la matriz A es cuadrada y Falso en caso contrario.

In [11]:
def esCuadrada(A):
    return A.shape[0] == A.shape[1]

print ("Matriz cuadrada: ", esCuadrada(matriz_cuadrada))
print ("Matriz no cuadrada: ", esCuadrada(matriz_no_cuadrada))

Matriz cuadrada:  True
Matriz no cuadrada:  False


Ejercicio 2. Desarrollar una funci´on triangSup(A) que devuelva la matriz U correspondiente a la matriz Triangular Superior de A sin su diagonal.

In [12]:
def triangSup(A):
    n = len(A)
    
    # Recorrer cada columna (excepto la última)
    for i in range(n - 1):
        # Evitar división por cero buscando un pivote diferente de cero
        if A[i][i] == 0:
            for k in range(i + 1, n):
                if A[k][i] != 0:
                    A[i], A[k] = A[k], A[i]  # Intercambiar filas
                    break
                    
        # Hacer ceros debajo del pivote actual
        for j in range(i + 1, n):
            factor = A[j][i] / A[i][i]
            for k in range(i, n):
                A[j][k] = A[j][k] - factor * A[i][k]
                
    return A

matriz_original = np.array([
    [2.0,  1.0, -1.0],
    [-3.0, -1.0,  2.0],
    [-2.0,  1.0,  2.0]
])

triangSup(matriz_original)

array([[ 2. ,  1. , -1. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  0. , -1. ]])

Ejercicio 3. Desarrollar una funci´on triangInf(A) que devuelva la matriz L correspondiente a la matriz Triangular Inferior de A sin su diagonal.

In [13]:
def triangInf(A):
    return triangSup(A)[::-1]

matriz_original = np.array([
    [2.0,  1.0, -1.0],
    [-3.0, -1.0,  2.0],
    [-2.0,  1.0,  2.0]
])

triangInf(matriz_original)

array([[ 0. ,  0. , -1. ],
       [ 0. ,  0.5,  0.5],
       [ 2. ,  1. , -1. ]])

Ejercicio 4. Desarrollar una funci´on diagonal(A) que devuelva la matriz D
correspondiente a la matriz diagonal de A.

In [14]:
def diagonal(A):
    triang = triangSup(A)
    n = len(A)

    for i in range(n-1):
        for j in range (i+1, n):
            triang[i][j] = 0

    return triang

diagonal(matriz_original)

array([[ 2. ,  0. ,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. ,  0. , -1. ]])

Ejercicio 5. Desarrollar una funci´on traza(A) que calcule la traza de una
matriz cualquiera A.

In [15]:
def traza(A):
    ans = 0
    n = len(A)

    for k in range(n):
        ans += sum(A[k])
    
    return ans

traza(matriz_original)

np.float64(1.5)

Ejercicio 6. Desarrollar una funci´on traspuesta(A) que devuelva la matriz
traspuesta de A.

In [19]:
def traspuesta(A):
    A_array = np.array(A)
    A_copy = A_array.copy()

    n = len(A_copy)
    for i in range(n):
        for j in range(i + 1, n):
            A_copy[i, j], A_copy[j, i] = A_copy[j, i], A_copy[i, j]

    return A_copy

matriz_original = np.array([
    [2.0,  1.0, -1.0],
    [-3.0, -1.0,  2.0],
    [-2.0,  1.0,  2.0]
])

print(matriz_original)
print("Traspuesta:")
print(traspuesta(matriz_original))

[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]
Traspuesta:
[[ 2. -3. -2.]
 [ 1. -1.  1.]
 [-1.  2.  2.]]


Ejercicio 7. Desarrollar una funci´on esSimetrica(A) que devuelve True si la
matriz A es sim´etrica y False en caso contrario.

In [ ]:
def esSimetrica(A):
    if not esCuadrada(A):
        return False
    
    n = len(A)

    for i in range(n):
        for j in range (n):
            if A[i][j] != A[j][i]:
                return False
    
    d = A[0][0]
    for i in range(n):
        if A[i][i] != d:
            return False

    return True

esSimetrica(matriz_original)

False

Ejercicio 8. Desarrollar una funci´on calcularAx(A,x) que recibe una matriz
A de tama˜no n × m y un vector x de largo m y devuelve un vector b de largo n
resultado de la multiplicaci´on vectorial de la matriz y el vector.

In [ ]:
M1 = np.arange(1,10).reshape(3,3)
V = [1, 1, 1]

def calcularAx(A, x):
    n = A.shape[0]
    m = A.shape[1]

    m = len(x)

    X = np.array(x)

    return A@X

calcularAx(M1, V)

array([ 6, 15, 24])

Ejercicio 9. Desarrollar una funci´on intercambiarFilas(A, i, j), que in-
tercambie las filas i y la j de la matriz A. El intercambio tiene que ser in-place.

Ejercicio 10. Desarrollar una funci´on sumar fila multiplo(A, i, j, s) que
a la fila i le sume la fila j multiplicada por un escalar s. Esta es una operaci´on
elemental clave en la eliminaci´on gaussiana. La operaci´on debe ser in-place.

Ejercicio 11. Desarrollar una funci´on esDiagonalmenteDominante(A) que de-
vuelva True si una matriz cuadrada A es estrictamente diagonalmente domi-
nante. Esto ocurre si para cada fila, el valor absoluto del elemento en la diagonal
es mayor que la suma de los valores absolutos de los dem´as elementos en esa
fila.